In [65]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import VotingRegressor, BaggingRegressor, RandomForestRegressor, GradientBoostingRegressor, StackingRegressor
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import mlflow
from mlflow.models import infer_signature
import xgboost as xgb

In [66]:
data = pd.read_csv("Cleaned_data_version_1.csv")
data = pd.DataFrame(data, index= None)

x = data.drop('salary_usd' , axis=1)
y = data['salary_usd']


X_train, X_test, y_train,y_test =train_test_split(x, y ,test_size= 0.25, random_state = 42)

In [68]:

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(random_state=42),
    "KNN": KNeighborsRegressor()
}

results = []

for name, model in models.items():

    # Training
    model.fit(X_train, y_train)

    # Prediction
    y_pred = model.predict(X_test)

    # Performance
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))

    results.append({
        "Model": name,
        "R2": r2,
        "MAE": mae,
        "RMSE": rmse
    })

results_df = pd.DataFrame(results)

results_df

               Model        R2           MAE          RMSE
0  Linear Regression  0.806975  18387.539857  24423.794761
1      Decision Tree  0.561610  25934.384000  36807.481153
2      Random Forest  0.799629  17571.938720  24884.189012
3  Gradient Boosting  0.823373  16578.704821  23363.351596
4                KNN -0.119989  46605.363520  58831.891102

In [69]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
    ExtraTreesRegressor,
    RandomForestRegressor
)
from sklearn.neighbors import KNeighborsRegressor

models = {
    "Linear Regression": LinearRegression(),

    "Ridge": Ridge(
        alpha=1.0
    ),

    "Lasso": Lasso(
        alpha=0.001,
        max_iter=10000
    ),

    "Decision Tree": DecisionTreeRegressor(
        max_depth=10,
        min_samples_split=10,
        min_samples_leaf=5,
        max_features=None,
        random_state=42
    ),

    "Random Forest": RandomForestRegressor(
        n_estimators=300,
        max_depth=15,
        min_samples_split=5,
        min_samples_leaf=2,
        max_features="sqrt",
        random_state=42,
        n_jobs=-1
    ),

    "Extra Trees": ExtraTreesRegressor(
        n_estimators=300,
        max_depth=15,
        min_samples_split=5,
        min_samples_leaf=2,
        max_features="sqrt",
        random_state=42,
        n_jobs=-1
    ),

    "Gradient Boosting": GradientBoostingRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=5,
        min_samples_split=5,
        min_samples_leaf=2,
        subsample=0.8,
        random_state=42
    ),

    "KNN": KNeighborsRegressor(
        n_neighbors=10,
        weights="distance",
        p=2
    )
}




from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np
import pandas as pd

results = []

for name, model in models.items():

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))

    results.append({
        "Model": name,
        "R2": r2,
        "MAE": mae,
        "RMSE": rmse
    })

results_df = pd.DataFrame(results)

results_df.sort_values("R2", ascending=False)

c:\Users\harsh\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.068e+11, tolerance: 1.146e+09
  model = cd_fast.enet_coordinate_descent(

               Model        R2           MAE          RMSE
6  Gradient Boosting  0.844527  15361.542110  21919.662593
2              Lasso  0.806975  18387.539209  24423.794699
0  Linear Regression  0.806975  18387.539857  24423.794761
1              Ridge  0.806922  18382.120392  24427.111112
5        Extra Trees  0.792663  18240.839837  25313.065462
4      Random Forest  0.771659  19314.628495  26564.294921
3      Decision Tree  0.670131  22227.563320  31928.356436
7                KNN -0.049871  45496.556403  56960.531693

In [70]:
from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    min_child_weight=3,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0,
    reg_alpha=0,
    reg_lambda=1,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("R2:", r2)
print("MAE:", mae)
print("RMSE:", rmse)

R2: 0.8463001251220703
MAE: 15391.619140625
RMSE: 21794.295033333838

In [71]:
# EDA Part 2 

data.columns

Index(['Unnamed: 0', 'job_title_AI Engineer', 'job_title_Analytics Engineer',
       'job_title_Business Intelligence Analyst',
       'job_title_Computer Vision Engineer', 'job_title_Data Analyst',
       'job_title_Data Engineer', 'job_title_Data Science Manager',
       'job_title_Data Scientist', 'job_title_LLM Engineer',
       'job_title_MLOps Engineer', 'job_title_Machine Learning Engineer',
       'job_title_Research Scientist', 'experience_level_0',
       'experience_level_1', 'experience_level_2', 'experience_level_3',
       'experience_level_4', 'employment_type_Contract',
       'employment_type_Freelance', 'employment_type_Full-time',
       'employment_type_Part-time', 'company_location_AU',
       'company_location_BR', 'company_location_CA', 'company_location_DE',
       'company_location_ES', 'company_location_FR', 'company_location_GB',
       'company_location_IN', 'company_location_NL', 'company_location_PL',
       'company_location_SG', 'company_location_US', 'industry_Consulting',
       'industry_Education', 'industry_Energy', 'industry_Finance',
       'industry_Government', 'industry_Healthcare', 'industry_Manufacturing',
       'industry_Media', 'industry_Retail', 'industry_Technology',
       'employee_residence_IN', 'education_level', 'company_size',
       'years_experience', 'has_ml_in_title', 'manages_people',
       'certifications_count', 'weekly_hours', 'salary_usd',
       'job_satisfaction_score', 'interviews_to_offer',
       'switched_jobs_last_year'],
      dtype='object')

In [72]:
#Renaming some columns name
data = data.rename(columns = {'experience_level_0': 'Entry(0-2)', 'experience_level_1': 'Mid(2-5)', 'experience_level_2': 'Senior', 'experience_level_3': 'Lead', 'experience_level_4': 'Executive'} )

In [73]:
pd.set_option("display.max_columns", None)

data

,Unnamed: 0,job_title_AI Engineer,job_title_Analytics Engineer,job_title_Business Intelligence Analyst,job_title_Computer Vision Engineer,job_title_Data Analyst,job_title_Data Engineer,job_title_Data Science Manager,job_title_Data Scientist,job_title_LLM Engineer,job_title_MLOps Engineer,job_title_Machine Learning Engineer,job_title_Research Scientist,Entry(0-2),Mid(2-5),Senior,Lead,Executive,employment_type_Contract,employment_type_Freelance,employment_type_Full-time,employment_type_Part-time,company_location_AU,company_location_BR,company_location_CA,company_location_DE,company_location_ES,company_location_FR,company_location_GB,company_location_IN,company_location_NL,company_location_PL,company_location_SG,company_location_US,industry_Consulting,industry_Education,industry_Energy,industry_Finance,industry_Government,industry_Healthcare,industry_Manufacturing,industry_Media,industry_Retail,industry_Technology,employee_residence_IN,education_level,company_size,years_experience,has_ml_in_title,manages_people,certifications_count,weekly_hours,salary_usd,job_satisfaction_score,interviews_to_offer,switched_jobs_last_year
0,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0,1.252729,0,1,0,0.595004,23844,-0.868897,1.147877,1
1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,2,-0.157964,1,0,1,-0.446977,170132,0.230676,-0.924702,0
2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,-1.734621,1,0,1,1.750951,83059,-0.575678,-1.753733,0
3,3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,1,0.277691,0,0,2,-0.528382,29531,-0.795592,-0.095670,0
4,4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1,-1.070766,0,0,2,0.627566,70105,-1.528641,-0.510186,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4995,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1,0.194709,0,0,2,-0.577225,38810,0.450590,-1.339218,0
4996,4996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1,1.024528,1,1,1,1.685828,123368,-0.868897,0.733361,0
4997,4997,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1,-0.054237,0,0,3,1.213680,86123,0.230676,0.318846,1
4998,4998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1,0.941546,1,0,1,-0.967968,76001,-0.502373,-0.510186,1
4999,4999,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1,-1.298966,0,0,2,-1.602925,49321,-0.062544,-0.924702,0

In [74]:
data.shape

(5000, 56)

In [75]:
data.columns

Index(['Unnamed: 0', 'job_title_AI Engineer', 'job_title_Analytics Engineer',
       'job_title_Business Intelligence Analyst',
       'job_title_Computer Vision Engineer', 'job_title_Data Analyst',
       'job_title_Data Engineer', 'job_title_Data Science Manager',
       'job_title_Data Scientist', 'job_title_LLM Engineer',
       'job_title_MLOps Engineer', 'job_title_Machine Learning Engineer',
       'job_title_Research Scientist', 'Entry(0-2)', 'Mid(2-5)', 'Senior',
       'Lead', 'Executive', 'employment_type_Contract',
       'employment_type_Freelance', 'employment_type_Full-time',
       'employment_type_Part-time', 'company_location_AU',
       'company_location_BR', 'company_location_CA', 'company_location_DE',
       'company_location_ES', 'company_location_FR', 'company_location_GB',
       'company_location_IN', 'company_location_NL', 'company_location_PL',
       'company_location_SG', 'company_location_US', 'industry_Consulting',
       'industry_Education', 'industry_Energy', 'industry_Finance',
       'industry_Government', 'industry_Healthcare', 'industry_Manufacturing',
       'industry_Media', 'industry_Retail', 'industry_Technology',
       'employee_residence_IN', 'education_level', 'company_size',
       'years_experience', 'has_ml_in_title', 'manages_people',
       'certifications_count', 'weekly_hours', 'salary_usd',
       'job_satisfaction_score', 'interviews_to_offer',
       'switched_jobs_last_year'],
      dtype='object')

In [76]:
droping_cols = ['has_ml_in_title', 'manages_people',
       'certifications_count', 'weekly_hours',
       'job_satisfaction_score', 'interviews_to_offer',
       'switched_jobs_last_year']

data = data.drop(columns = droping_cols, axis= 1)

In [77]:
data.shape
data.columns

Index(['Unnamed: 0', 'job_title_AI Engineer', 'job_title_Analytics Engineer',
       'job_title_Business Intelligence Analyst',
       'job_title_Computer Vision Engineer', 'job_title_Data Analyst',
       'job_title_Data Engineer', 'job_title_Data Science Manager',
       'job_title_Data Scientist', 'job_title_LLM Engineer',
       'job_title_MLOps Engineer', 'job_title_Machine Learning Engineer',
       'job_title_Research Scientist', 'Entry(0-2)', 'Mid(2-5)', 'Senior',
       'Lead', 'Executive', 'employment_type_Contract',
       'employment_type_Freelance', 'employment_type_Full-time',
       'employment_type_Part-time', 'company_location_AU',
       'company_location_BR', 'company_location_CA', 'company_location_DE',
       'company_location_ES', 'company_location_FR', 'company_location_GB',
       'company_location_IN', 'company_location_NL', 'company_location_PL',
       'company_location_SG', 'company_location_US', 'industry_Consulting',
       'industry_Education', 'industry_Energy', 'industry_Finance',
       'industry_Government', 'industry_Healthcare', 'industry_Manufacturing',
       'industry_Media', 'industry_Retail', 'industry_Technology',
       'employee_residence_IN', 'education_level', 'company_size',
       'years_experience', 'salary_usd'],
      dtype='object')

In [78]:
data.to_csv("Cleaned_data_version_2.csv", index= None)